create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  party_id text not null,
  dish_name text not null,
  category text not null default 'Other',
  quantity integer not null default 0 check (quantity >= 0),
  bill_quantity integer not null default 0 check (bill_quantity >= 0),
  is_custom boolean not null default false,
  food_type text not null default 'veg' check (food_type in ('veg', 'nonveg')),
  created_at timestamptz not null default now(),
  unique (party_id, dish_name, category)
);


-- If this table already existed, add the food type column without deleting existing orders.
alter table public.orders add column if not exists food_type text not null default 'veg';
alter table public.orders add column if not exists bill_quantity integer not null default 0;
alter table public.orders drop constraint if exists orders_bill_quantity_check;
alter table public.orders add constraint orders_bill_quantity_check check (bill_quantity >= 0);
-- Preserve any existing quantities as the current bill total when upgrading.
update public.orders set bill_quantity = quantity where bill_quantity = 0 and quantity > 0;

alter table public.orders drop constraint if exists orders_food_type_check;
alter table public.orders add constraint orders_food_type_check check (food_type in ('veg', 'nonveg'));

alter table public.orders enable row level security;

-- This app intentionally allows anyone with a party URL to read/write that party's order.
-- Do not use this policy for sensitive data.
drop policy if exists "public read orders" on public.orders;
drop policy if exists "public insert orders" on public.orders;
drop policy if exists "public update orders" on public.orders;
drop policy if exists "public delete orders" on public.orders;

create policy "public read orders"
on public.orders for select
using (true);

create policy "public insert orders"
on public.orders for insert
with check (true);

create policy "public update orders"
on public.orders for update
using (true)
with check (true);

create policy "public delete orders"
on public.orders for delete
using (true);

-- Enable realtime for this table.
alter table public.orders replica identity full;

-- Supabase projects normally already have this publication. The DO block avoids failing if it exists.
do $$
begin
  alter publication supabase_realtime add table public.orders;
exception
  when duplicate_object then null;
end $$;
